name: Release
on:
  workflow_dispatch:
    branches:
      - 'release/**'

  workflow_run:
    workflows:
      - "Node.js CI"
    branches:
      - master
      - 'release/**'
    types:
      - completed
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Run build
        run: node make.js build
      - name: Test
        run: yarn lint && yarn test
      - name: Deploy to NPM
        if: github.repository_owner == 'Rhosys' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: After build
        if: github.repository_owner == 'Rhosys' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node make.js after_build
      - name: Create Github Release and Tag
        if: github.repository_owner == 'Rhosys' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: |
          git tag ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER
          git push origin ${GITHUB_REF/refs\/heads\/release\//}.$GITHUB_RUN_NUMBER
